/**
 * Pool→shell floating-layer action callback contract—E5.7#97.
 *
 * Originally module-local types in preload-shell.ts (E5.7#15/#16/#17/#39),
 * but these are cross-stack wire payloads too—consolidated into this directory; the shell preload and the API type layer both import type.
 * Note the distinction from poolQuickPick.ts / poolDialog.ts / poolFloatingPanel.ts: those are shell→pool render data DTOs,
 * while these are pool→shell action callbacks (the shell side re-resolves the original item by actionId).
 * E6#72: Toast action callbacks removed entirely—the bottom-right narrow-card path was removed; notification actions are unified through layout.statusBar.notif panel buttons.
 */

/** QuickPick action—select/highlight/close/itemAction report back by key */
export interface PoolQuickPickAction {
  type: string;
  key?: string;
  actionId?: string;
}

/** Dialog action—confirm/cancel reported back; the shell settles the Promise */
export interface PoolDialogAction {
  type: string;
}

/** Floating panel action—action reported back by actionId (open-in/close); the shell settles the Promise (E5.8#37 type B) */
export interface PoolFloatingPanelAction {
  type: string;
  actionId?: string;
}

/** Memory pressure notification—the main process's window-manager sampled above threshold (E5.7#39) */
export interface MemoryPressureData {
  totalRSS: number;
  threshold: number;
}

/** Pool-ready notification payload—the main process resolves windowId by sender and forwards it to the shell (E5.8#43-1 A3 multi-window ready flow) */
export interface PoolReadyPayload {
  windowId: string;
}

/** Shell→main: create pool window request—windowId generated by the shell (tabState ownership), bounds optional (E5.8#43-1 A4 multi-window foundation) */
export interface CreatePoolWindowRequest {
  windowId: string;
  width?: number;
  height?: number;
  x?: number;
  y?: number;
}

/** Main→shell: pool window closed by the OS notification (user clicks × / OS closes the window)—the shell handles tabs per windowId under the window policy (E5.8#43-1 A4) */
export interface PoolWindowClosedPayload {
  windowId: string;
}

/** E5.8#43-3: pool window position/size change rect—reported by main-process moved/resized events (the shell updates the registry by windowId + persists it, A6).
 *  Not an independent contract entry (the contract generator's walkRefs force-exports anything referenced into linkdesk.d.ts)—the source does not export it, so knip does not flag dead code. */
interface WindowBounds {
  x: number;
  y: number;
  width: number;
  height: number;
}

/** Main→shell: pool window bounds change notification (user moves/resizes the window)—the shell persists the floating window position (I9-14 position/size record) */
export interface PoolWindowBoundsPayload {
  windowId: string;
  bounds: WindowBounds;
}

/** E5.8#44-B: TabBar viewport rect—reported by the pool side via getBoundingClientRect (data source for dock/release merge-window hit testing).
 *  Coordinates are viewport-relative (0,0 = top-left of the window content area); the shell holds the authoritative window bounds and converts to screen (bounds.x + rect.left).
 *  groupId is carried—after a hit, mergeTabToWindow goes straight to the target group. */
export interface TabBarViewportRect {
  groupId: string;
  left: number;
  top: number;
  width: number;
  height: number;
}

/** Pool→shell: TabBar rects report payload—the main process resolves windowId by sender and attaches it (E5.8#44-B) */
export interface TabBarRectsPayload {
  windowId: string;
  rects: TabBarViewportRect[];
}

/** E5.8#44-C: drag position report payload—reported by the pool's drag-out gesture (mousemove for the whole duration after pickup); the shell excludes the source window and converts to screen coordinates for dock hit testing.
 *  Coordinates are screen coordinates (e.screenX/screenY—window bounds are screen coordinates too, so hit testing works directly). canceled = Esc cancel (keydown carries no coordinates). */
export interface TabDragPositionPayload {
  tabId: string;
  screenX: number;
  screenY: number;
  /** Esc canceled the drag—the shell clears the dock hint (keydown carries no coordinates, only sets the flag; screenX/screenY are filled with 0) */
  canceled?: boolean;
  /** E5.8#46.19: title of the dragged tab—reported by the pool so the main process can render text in the ghost window (the main process holds no tabState; the title comes from the pool). Ignored by the shell/dock */
  title?: string;
  /** E5.8#46.19: whether the cursor is outside the source window (screen coordinates compared against winScreenX+viewport size, same source as the onMouseUp outside-window check)—
   *  outside → the main process shows the OS ghost (a DOM floating block outside the window would be clipped); inside → the OS ghost hides (the DOM floating block stays visible). Ignored by the shell/dock */
  outside?: boolean;
  /** E5.8#46.19 evolution: drag ghost appearance—theme three colors (the source pool reads --bg-card/--border/--text-primary via getComputedStyle,
   *  all plain hex values) + the dragged tab's icon (E6#69g: the pool narrows the tab.icon discriminated union into a form the ghost window can render—emoji text or an img
   *  URL; codicon/lucide have no glyph font injected → null, iconKind distinguishes the rendering).
   *  Consumed by the main process only when outside=true (outside the window); ignored by the shell/dock. Optional—old pools may omit it (no cap).
   *  iconKind determination is the same as the DragOverlays floating block (emoji: direct text render; img: image URL). */
  ghost?: {
    theme: { bg: string; border: string; text: string };
    icon: string | null;
    iconKind: "emoji" | "img" | null;
  };
}

/** Pool→shell: drag position report payload—the main process resolves sourceWindowId by sender and attaches it (E5.8#44-C source-window exclusion—the pool never knows its own windowId) */
export type ShellTabDragPosition = TabDragPositionPayload & { sourceWindowId: string };

/** Shell→pool: dock hint payload—the target window's TabBar insert indicator (groupId hit) / clear (groupId null = no dock target, clear everything).
 *  E5.8#46.10: on a groupId hit, viewportX/Y are carried—the cursor position in the target window's viewport coordinates (the shell converts from screen coordinates minus the window bounds origin),
 *  and the target pool uses it to compute the insert gap (the vertical-line landing spot, reusing computeTabInsertIndex). */
export interface AdsorbHintPayload {
  groupId: string | null;
  viewportX?: number;
  viewportY?: number;
}

/** Pool→shell: dock insert gap callback—whenever the target pool computes a new gap (the vertical-line landing spot) it reports it; the shell stores it in the dock registry for precise placement on release-and-merge.
 *  windowId is injected by the main process based on the sender (the pool never knows its own windowId, settled in E5.8#44). */
export interface AdsorbIndexPayload {
  windowId: string;
  groupId: string;
  /** Insert gap 0..tabs.length (the vertical-line landing spot)—on release, the merge lands exactly in the gap the line points at (the hint never lies) */
  insertIndex: number;
}
