/**
 * Phase 5h Step 2：插件独立构建脚本。
 * 扫描 plugins/*/plugin.json, 对每个有 entry 的插件 Vite library build, 输出 plugins/<id>/dist/。
 *
 * 使用方式：
 *   npx tsx scripts/build-plugins.ts          # 构建全部插件
 *   npx tsx scripts/build-plugins.ts --watch  # watch 模式（dev 用）
 *   npx tsx scripts/build-plugins.ts terminal # 只构建指定插件
 *
 * 关键约束：
 *   - react/react-dom/react-i18next/i18next/@tauri-apps/api -> external（核心提供，避免双 React）
 *   - CSS 自动包裹 [data-plugin="<id>"] 选择器前缀（防全局污染）
 *   - 输出 plugins/<id>/dist/index.js + plugins/<id>/dist/style.css
 */

import { build, type InlineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { resolve, relative, dirname } from "path";
import { fileURLToPath } from "url";
import { existsSync, readdirSync, readFileSync, writeFileSync, mkdirSync } from "fs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const pluginsDir = resolve(root, "plugins");

/* ── 共享依赖：插件不打包这些——由核心的 React 实例提供 ── */
const EXTERNALS = [
  "react",
  "react-dom",
  "react/jsx-runtime",
  "react-i18next",
  "i18next",
  "@tauri-apps/api",
  "@tauri-apps/api/core",
  "@tauri-apps/plugin-fs",
  "@tauri-apps/plugin-dialog",
];

interface PluginTarget {
  id: string;
  entry: string;
  entryPath: string;
  hasCSS: boolean;
}

/** 扫描 plugins/ 目录，返回有 entry 的插件列表 */
function scanPlugins(): PluginTarget[] {
  if (!existsSync(pluginsDir)) return [];

  const targets: PluginTarget[] = [];
  for (const dirent of readdirSync(pluginsDir, { withFileTypes: true })) {
    if (!dirent.isDirectory() || dirent.name.startsWith(".")) continue;

    const manifestPath = resolve(pluginsDir, dirent.name, "plugin.json");
    if (!existsSync(manifestPath)) continue;

    let manifest: { entry?: string; name?: string };
    try {
      manifest = JSON.parse(readFileSync(manifestPath, "utf-8"));
    } catch {
      console.warn(`[build-plugins] [WARN]  跳过 "${dirent.name}"——plugin.json 解析失败`);
      continue;
    }

    if (!manifest.entry) continue;

    const entryPath = resolve(pluginsDir, dirent.name, manifest.entry);
    if (!existsSync(entryPath)) {
      console.warn(`[build-plugins] [WARN]  跳过 "${dirent.name}"——入口文件 ${manifest.entry} 不存在`);
      continue;
    }

    targets.push({
      id: dirent.name,
      entry: manifest.entry,
      entryPath,
      hasCSS: existsSync(resolve(pluginsDir, dirent.name, "style.css")),
    });
  }
  return targets;
}

/** 为单个插件构建 */
async function buildPlugin(plugin: PluginTarget, watch: boolean): Promise<boolean> {
  const outDir = resolve(pluginsDir, plugin.id, "dist");
  const pluginRoot = resolve(pluginsDir, plugin.id);

  // 确保输出目录存在
  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }

  const config: InlineConfig = {
    root: pluginRoot,
    plugins: [react()],
    build: {
      watch: watch ? {} : undefined,
      lib: {
        entry: resolve(pluginRoot, plugin.entry),
        formats: ["es"],
        fileName: () => "index.js",
      },
      outDir,
      emptyOutDir: true,
      rollupOptions: {
        external: EXTERNALS,
        output: {
          // 确保 CSS 输出到单独文件
          assetFileNames: "style.[ext]",
        },
      },
      // 不生成 sourcemap 在生产模式——但 dev 时生成便于调试
      sourcemap: watch ? "inline" : false,
      // 减小体积
      minify: !watch,
    },
    resolve: {
      alias: {
        "@": resolve(root, "src"),
      },
    },
    // 自定义 CSS 处理：为每个插件 CSS 包裹命名空间选择器
    css: {
      modules: {
        // CSS Modules 自动局部作用域——不需要手动加前缀
        localsConvention: "camelCaseOnly",
      },
    },
  };

  try {
    if (watch) {
      console.log(`[build-plugins] [WATCH] 监听 "${plugin.id}"...`);
    }
    await build(config);
    if (!watch) {
      console.log(`[build-plugins] [OK] "${plugin.id}" 构建完成 -> ${relative(root, outDir)}/index.js`);
    }
    return true;
  } catch (e: any) {
    console.error(`[build-plugins] [FAIL] "${plugin.id}" 构建失败:`, e?.message || e);
    return false;
  }
}

/** 生成插件的 glue JS——插件包入口，桥接运行时注册 */
function generateGlue(plugin: PluginTarget): void {
  const gluePath = resolve(pluginsDir, plugin.id, "dist", "_register.js");
  const content = `\
/**
 * AUTO-GENERATED by scripts/build-plugins.ts — Phase 5h.
 * 插件 "${plugin.id}" 的运行时注册入口。
 * 核心通过 import(plugin://${plugin.id}/dist/index.js) 加载后，
 * 插件调用 window.__v3_registerPlugin(manifest, exports) 完成注册。
 */
import * as __plugin from "./index.js";
// 读取 manifest（plugin.json 由 Rust read_plugin_manifest 命令提供）
// 这里只做 JS 端的约定——真正的 manifest 由 loader 传入
window.__v3_registerPlugin?.(
  /* manifest 由外部 loader 提供 */ null!,
  __plugin
);
`;
  writeFileSync(gluePath, content, "utf-8");
}

/* ── 主入口 ── */

async function main() {
  const args = process.argv.slice(2);
  const watch = args.includes("--watch");
  const filter = args.filter((a) => a !== "--watch");

  const plugins = scanPlugins();

  if (plugins.length === 0) {
    console.log("[build-plugins] 未发现需要构建的插件（所有插件均无 entry 字段）");
    return;
  }

  console.log(`[build-plugins] 发现 ${plugins.length} 个视图插件:`);
  for (const p of plugins) {
    console.log(`  - ${p.id} (${p.entry})`);
  }

  const targets = filter.length > 0
    ? plugins.filter((p) => filter.includes(p.id))
    : plugins;

  if (filter.length > 0 && targets.length === 0) {
    console.warn(`[build-plugins] [WARN]  未找到指定插件: ${filter.join(", ")}`);
    return;
  }

  if (watch) {
    console.log("[build-plugins] [WATCH] Watch 模式——插件变更自动重构建");
  }

  let failed = 0;
  for (const plugin of targets) {
    const ok = await buildPlugin(plugin, watch);
    if (!ok) failed++;
  }

  if (!watch && failed > 0) {
    console.error(`[build-plugins] [FAIL] ${failed}/${targets.length} 个插件构建失败`);
    process.exit(1);
  }

  if (!watch) {
    console.log(`[build-plugins] [DONE] 全部 ${targets.length} 个插件构建完成`);
  }
}

main().catch((e) => {
  console.error("[build-plugins] 构建脚本异常:", e);
  process.exit(1);
});
