/**
 * 🔥 linkdesk-mock.generated.ts——dev 宿主 window.linkdesk mock 树（自动生成，勿手改）
 *
 * 生成源：src/core/api/linkdesk-api.ts + linkdesk-api/（LinkDeskAPI 交集——与 linkdesk.d.ts 同一标注源）
 * 生成器：scripts/generate-contract.mjs（E6#27 第三产物，杜绝 mock/preload 双份漂移）
 * 改契约源 → 跑 `node scripts/generate-contract.mjs`（npm run check 里 contracts:check 三产物逐字节强制）
 *
 * 消费方：packages/plugin-sdk/dev-host/mock.ts——injectDevMockApi() 用 Proxy 包本树：
 *   树内方法 = 类型驱动中性默认 + 调用即打 [linkdesk-mock] 日志（mock vs 真 IPC 可感知）；
 *   树外路径（契约里不存在的方法名） = Proxy 抛「不在 linkdesk API 契约」。
 * 默认值策略（"不崩 + 可感知"，详见 02-本地预览环境.md §10.2）：
 *   Promise<void/…数据对象> → async 返 undefined；Promise<数组> → []；Promise<string/boolean> → ""/false；
 *   void → noop（registerCommand 等每插件必调，绝不抛）；返回退订句柄（onChange 等）→ noop 函数；
 *   其余同步 → ""/undefined。真数据/真行为走真实 IPC / linkdesk-plugin-sdk dev --real（E6#28.5）。
 */
export const linkdeskMock: Record<string, unknown> = {
  commands: {
    execute: async (..._args: unknown[]) => { console.info("[linkdesk-mock] commands.execute", ..._args); },
    executeCommand: async (..._args: unknown[]) => { console.info("[linkdesk-mock] commands.executeCommand", ..._args); },
    registerCommand: (..._args: unknown[]) => { console.info("[linkdesk-mock] commands.registerCommand", ..._args); },
    unregisterCommands: (..._args: unknown[]) => { console.info("[linkdesk-mock] commands.unregisterCommands", ..._args); },
    getCommands: async (..._args: unknown[]) => { console.info("[linkdesk-mock] commands.getCommands", ..._args); return []; },
    _executeShellLocal: async (..._args: unknown[]) => { console.info("[linkdesk-mock] commands._executeShellLocal", ..._args); },
    _setCommandMissHandler: (..._args: unknown[]) => { console.info("[linkdesk-mock] commands._setCommandMissHandler", ..._args); },
  },
  configuration: {
    get: async (..._args: unknown[]) => { console.info("[linkdesk-mock] configuration.get", ..._args); },
    set: async (..._args: unknown[]) => { console.info("[linkdesk-mock] configuration.set", ..._args); },
    getSchema: async (..._args: unknown[]) => { console.info("[linkdesk-mock] configuration.getSchema", ..._args); },
    onChange: (..._args: unknown[]) => { console.info("[linkdesk-mock] configuration.onChange", ..._args); return () => {}; },
    getConfigurationContributions: async (..._args: unknown[]) => { console.info("[linkdesk-mock] configuration.getConfigurationContributions", ..._args); return []; },
    inspectConfiguration: async (..._args: unknown[]) => { console.info("[linkdesk-mock] configuration.inspectConfiguration", ..._args); },
    getUserSettings: async (..._args: unknown[]) => { console.info("[linkdesk-mock] configuration.getUserSettings", ..._args); },
    onDidChangeConfiguration: (..._args: unknown[]) => { console.info("[linkdesk-mock] configuration.onDidChangeConfiguration", ..._args); return () => {}; },
    onPluginLifecycleChange: (..._args: unknown[]) => { console.info("[linkdesk-mock] configuration.onPluginLifecycleChange", ..._args); return () => {}; },
    consumeSettingsGroup: async (..._args: unknown[]) => { console.info("[linkdesk-mock] configuration.consumeSettingsGroup", ..._args); },
    onRequestSettingsGroup: (..._args: unknown[]) => { console.info("[linkdesk-mock] configuration.onRequestSettingsGroup", ..._args); return () => {}; },
    consumeScrollToSetting: async (..._args: unknown[]) => { console.info("[linkdesk-mock] configuration.consumeScrollToSetting", ..._args); },
    onRequestScrollToSetting: (..._args: unknown[]) => { console.info("[linkdesk-mock] configuration.onRequestScrollToSetting", ..._args); return () => {}; },
    consumeOpenKeybindings: async (..._args: unknown[]) => { console.info("[linkdesk-mock] configuration.consumeOpenKeybindings", ..._args); },
    onRequestOpenKeybindings: (..._args: unknown[]) => { console.info("[linkdesk-mock] configuration.onRequestOpenKeybindings", ..._args); return () => {}; },
  },
  config: {
    get: async (..._args: unknown[]) => { console.info("[linkdesk-mock] config.get", ..._args); },
    set: async (..._args: unknown[]) => { console.info("[linkdesk-mock] config.set", ..._args); },
    getSchema: async (..._args: unknown[]) => { console.info("[linkdesk-mock] config.getSchema", ..._args); },
    onChange: (..._args: unknown[]) => { console.info("[linkdesk-mock] config.onChange", ..._args); return () => {}; },
    getConfigurationContributions: async (..._args: unknown[]) => { console.info("[linkdesk-mock] config.getConfigurationContributions", ..._args); return []; },
    inspectConfiguration: async (..._args: unknown[]) => { console.info("[linkdesk-mock] config.inspectConfiguration", ..._args); },
    getUserSettings: async (..._args: unknown[]) => { console.info("[linkdesk-mock] config.getUserSettings", ..._args); },
    onDidChangeConfiguration: (..._args: unknown[]) => { console.info("[linkdesk-mock] config.onDidChangeConfiguration", ..._args); return () => {}; },
    onPluginLifecycleChange: (..._args: unknown[]) => { console.info("[linkdesk-mock] config.onPluginLifecycleChange", ..._args); return () => {}; },
    consumeSettingsGroup: async (..._args: unknown[]) => { console.info("[linkdesk-mock] config.consumeSettingsGroup", ..._args); },
    onRequestSettingsGroup: (..._args: unknown[]) => { console.info("[linkdesk-mock] config.onRequestSettingsGroup", ..._args); return () => {}; },
    consumeScrollToSetting: async (..._args: unknown[]) => { console.info("[linkdesk-mock] config.consumeScrollToSetting", ..._args); },
    onRequestScrollToSetting: (..._args: unknown[]) => { console.info("[linkdesk-mock] config.onRequestScrollToSetting", ..._args); return () => {}; },
    consumeOpenKeybindings: async (..._args: unknown[]) => { console.info("[linkdesk-mock] config.consumeOpenKeybindings", ..._args); },
    onRequestOpenKeybindings: (..._args: unknown[]) => { console.info("[linkdesk-mock] config.onRequestOpenKeybindings", ..._args); return () => {}; },
  },
  theme: {
    getCurrent: async (..._args: unknown[]) => { console.info("[linkdesk-mock] theme.getCurrent", ..._args); return ""; },
    getAvailable: async (..._args: unknown[]) => { console.info("[linkdesk-mock] theme.getAvailable", ..._args); return []; },
    apply: async (..._args: unknown[]) => { console.info("[linkdesk-mock] theme.apply", ..._args); },
    listRecipes: async (..._args: unknown[]) => { console.info("[linkdesk-mock] theme.listRecipes", ..._args); return []; },
    getActive: async (..._args: unknown[]) => { console.info("[linkdesk-mock] theme.getActive", ..._args); },
    getEffectiveTokens: async (..._args: unknown[]) => { console.info("[linkdesk-mock] theme.getEffectiveTokens", ..._args); },
    setRecipe: async (..._args: unknown[]) => { console.info("[linkdesk-mock] theme.setRecipe", ..._args); },
    setColorway: async (..._args: unknown[]) => { console.info("[linkdesk-mock] theme.setColorway", ..._args); },
    resetAppearance: async (..._args: unknown[]) => { console.info("[linkdesk-mock] theme.resetAppearance", ..._args); },
    resetMix: async (..._args: unknown[]) => { console.info("[linkdesk-mock] theme.resetMix", ..._args); },
    getBaselineSeeds: async (..._args: unknown[]) => { console.info("[linkdesk-mock] theme.getBaselineSeeds", ..._args); },
  },
  language: {
    getCurrent: async (..._args: unknown[]) => { console.info("[linkdesk-mock] language.getCurrent", ..._args); return ""; },
    getAvailable: async (..._args: unknown[]) => { console.info("[linkdesk-mock] language.getAvailable", ..._args); return []; },
    set: async (..._args: unknown[]) => { console.info("[linkdesk-mock] language.set", ..._args); },
    getInitial: (..._args: unknown[]) => { console.info("[linkdesk-mock] language.getInitial", ..._args); },
    onChange: (..._args: unknown[]) => { console.info("[linkdesk-mock] language.onChange", ..._args); return () => {}; },
  },
  appearance: {
    importImage: async (..._args: unknown[]) => { console.info("[linkdesk-mock] appearance.importImage", ..._args); return ""; },
    revealStorage: async (..._args: unknown[]) => { console.info("[linkdesk-mock] appearance.revealStorage", ..._args); },
  },
  tabs: {
    create: async (..._args: unknown[]) => { console.info("[linkdesk-mock] tabs.create", ..._args); },
    openOrFocus: async (..._args: unknown[]) => { console.info("[linkdesk-mock] tabs.openOrFocus", ..._args); },
    focus: async (..._args: unknown[]) => { console.info("[linkdesk-mock] tabs.focus", ..._args); },
    close: async (..._args: unknown[]) => { console.info("[linkdesk-mock] tabs.close", ..._args); },
    focusBySourceId: async (..._args: unknown[]) => { console.info("[linkdesk-mock] tabs.focusBySourceId", ..._args); },
    updateLabelBySourceId: async (..._args: unknown[]) => { console.info("[linkdesk-mock] tabs.updateLabelBySourceId", ..._args); },
    closeBySourceId: async (..._args: unknown[]) => { console.info("[linkdesk-mock] tabs.closeBySourceId", ..._args); },
    onDidChangeActiveTab: (..._args: unknown[]) => { console.info("[linkdesk-mock] tabs.onDidChangeActiveTab", ..._args); return () => {}; },
  },
  keybindings: {
    getKeybindings: async (..._args: unknown[]) => { console.info("[linkdesk-mock] keybindings.getKeybindings", ..._args); return []; },
    getConflicts: async (..._args: unknown[]) => { console.info("[linkdesk-mock] keybindings.getConflicts", ..._args); },
    registerKeybinding: async (..._args: unknown[]) => { console.info("[linkdesk-mock] keybindings.registerKeybinding", ..._args); },
    saveUserKeybindings: async (..._args: unknown[]) => { console.info("[linkdesk-mock] keybindings.saveUserKeybindings", ..._args); },
    removeKeybindingForCommand: async (..._args: unknown[]) => { console.info("[linkdesk-mock] keybindings.removeKeybindingForCommand", ..._args); },
    resetKeybindingToDefault: async (..._args: unknown[]) => { console.info("[linkdesk-mock] keybindings.resetKeybindingToDefault", ..._args); },
    findKeybindingForCommand: async (..._args: unknown[]) => { console.info("[linkdesk-mock] keybindings.findKeybindingForCommand", ..._args); },
    setKeybindingCaptureActive: async (..._args: unknown[]) => { console.info("[linkdesk-mock] keybindings.setKeybindingCaptureActive", ..._args); },
    keyboardEventToKeyString: (..._args: unknown[]) => { console.info("[linkdesk-mock] keybindings.keyboardEventToKeyString", ..._args); return ""; },
    onChange: (..._args: unknown[]) => { console.info("[linkdesk-mock] keybindings.onChange", ..._args); return () => {}; },
    syncToMainProcess: async (..._args: unknown[]) => { console.info("[linkdesk-mock] keybindings.syncToMainProcess", ..._args); },
    onForwardedEvent: (..._args: unknown[]) => { console.info("[linkdesk-mock] keybindings.onForwardedEvent", ..._args); return () => {}; },
  },
  notifications: {
    show: async (..._args: unknown[]) => { console.info("[linkdesk-mock] notifications.show", ..._args); },
  },
  menu: {
    registerItems: async (..._args: unknown[]) => { console.info("[linkdesk-mock] menu.registerItems", ..._args); },
    getItems: async (..._args: unknown[]) => { console.info("[linkdesk-mock] menu.getItems", ..._args); return []; },
  },
  contextKey: {
    set: async (..._args: unknown[]) => { console.info("[linkdesk-mock] contextKey.set", ..._args); },
    _getValue: (..._args: unknown[]) => { console.info("[linkdesk-mock] contextKey._getValue", ..._args); },
  },
  dialog: {
    confirm: async (..._args: unknown[]) => { console.info("[linkdesk-mock] dialog.confirm", ..._args); return false; },
    alert: async (..._args: unknown[]) => { console.info("[linkdesk-mock] dialog.alert", ..._args); },
    open: async (..._args: unknown[]) => { console.info("[linkdesk-mock] dialog.open", ..._args); },
    openFile: async (..._args: unknown[]) => { console.info("[linkdesk-mock] dialog.openFile", ..._args); },
    confirmContent: async (..._args: unknown[]) => { console.info("[linkdesk-mock] dialog.confirmContent", ..._args); return false; },
  },
  quickPick: {
    show: async (..._args: unknown[]) => { console.info("[linkdesk-mock] quickPick.show", ..._args); },
  },
  quickPickHost: {
    registerHost: (..._args: unknown[]) => { console.info("[linkdesk-mock] quickPickHost.registerHost", ..._args); return () => {}; },
    onShow: (..._args: unknown[]) => { console.info("[linkdesk-mock] quickPickHost.onShow", ..._args); return () => {}; },
    select: (..._args: unknown[]) => { console.info("[linkdesk-mock] quickPickHost.select", ..._args); },
    highlight: (..._args: unknown[]) => { console.info("[linkdesk-mock] quickPickHost.highlight", ..._args); },
    close: (..._args: unknown[]) => { console.info("[linkdesk-mock] quickPickHost.close", ..._args); },
    itemAction: (..._args: unknown[]) => { console.info("[linkdesk-mock] quickPickHost.itemAction", ..._args); },
  },
  dialogHost: {
    onShow: (..._args: unknown[]) => { console.info("[linkdesk-mock] dialogHost.onShow", ..._args); return () => {}; },
    current: (..._args: unknown[]) => { console.info("[linkdesk-mock] dialogHost.current", ..._args); },
    confirm: (..._args: unknown[]) => { console.info("[linkdesk-mock] dialogHost.confirm", ..._args); },
    cancel: (..._args: unknown[]) => { console.info("[linkdesk-mock] dialogHost.cancel", ..._args); },
  },
  floatingPanelHost: {
    onShow: (..._args: unknown[]) => { console.info("[linkdesk-mock] floatingPanelHost.onShow", ..._args); return () => {}; },
    action: (..._args: unknown[]) => { console.info("[linkdesk-mock] floatingPanelHost.action", ..._args); },
  },
  serial: {
    listPorts: async (..._args: unknown[]) => { console.info("[linkdesk-mock] serial.listPorts", ..._args); return []; },
    getStatus: async (..._args: unknown[]) => { console.info("[linkdesk-mock] serial.getStatus", ..._args); return []; },
    openPort: async (..._args: unknown[]) => { console.info("[linkdesk-mock] serial.openPort", ..._args); },
    closePort: async (..._args: unknown[]) => { console.info("[linkdesk-mock] serial.closePort", ..._args); },
    sendData: async (..._args: unknown[]) => { console.info("[linkdesk-mock] serial.sendData", ..._args); },
    sendText: async (..._args: unknown[]) => { console.info("[linkdesk-mock] serial.sendText", ..._args); },
    setDtr: async (..._args: unknown[]) => { console.info("[linkdesk-mock] serial.setDtr", ..._args); },
    setRts: async (..._args: unknown[]) => { console.info("[linkdesk-mock] serial.setRts", ..._args); },
    onData: (..._args: unknown[]) => { console.info("[linkdesk-mock] serial.onData", ..._args); return () => {}; },
    onStats: (..._args: unknown[]) => { console.info("[linkdesk-mock] serial.onStats", ..._args); return () => {}; },
    onSystem: (..._args: unknown[]) => { console.info("[linkdesk-mock] serial.onSystem", ..._args); return () => {}; },
  },
  clipboard: {
    readText: async (..._args: unknown[]) => { console.info("[linkdesk-mock] clipboard.readText", ..._args); return ""; },
    writeText: async (..._args: unknown[]) => { console.info("[linkdesk-mock] clipboard.writeText", ..._args); },
    writeFileList: async (..._args: unknown[]) => { console.info("[linkdesk-mock] clipboard.writeFileList", ..._args); },
  },
  p2p: {
    send: (..._args: unknown[]) => { console.info("[linkdesk-mock] p2p.send", ..._args); },
    on: (..._args: unknown[]) => { console.info("[linkdesk-mock] p2p.on", ..._args); return () => {}; },
  },
  events: {
    on: (..._args: unknown[]) => { console.info("[linkdesk-mock] events.on", ..._args); return () => {}; },
    emit: (..._args: unknown[]) => { console.info("[linkdesk-mock] events.emit", ..._args); },
    heartbeat: (..._args: unknown[]) => { console.info("[linkdesk-mock] events.heartbeat", ..._args); },
    notifyTheme: (..._args: unknown[]) => { console.info("[linkdesk-mock] events.notifyTheme", ..._args); },
  },
  pluginState: {
    get: async (..._args: unknown[]) => { console.info("[linkdesk-mock] pluginState.get", ..._args); },
    set: async (..._args: unknown[]) => { console.info("[linkdesk-mock] pluginState.set", ..._args); },
    onChange: (..._args: unknown[]) => { console.info("[linkdesk-mock] pluginState.onChange", ..._args); return () => {}; },
  },
  workspace: {
    getFolders: async (..._args: unknown[]) => { console.info("[linkdesk-mock] workspace.getFolders", ..._args); return []; },
    getActive: async (..._args: unknown[]) => { console.info("[linkdesk-mock] workspace.getActive", ..._args); },
    setActive: async (..._args: unknown[]) => { console.info("[linkdesk-mock] workspace.setActive", ..._args); },
    openFolder: async (..._args: unknown[]) => { console.info("[linkdesk-mock] workspace.openFolder", ..._args); },
    addFolder: async (..._args: unknown[]) => { console.info("[linkdesk-mock] workspace.addFolder", ..._args); },
    removeFolder: async (..._args: unknown[]) => { console.info("[linkdesk-mock] workspace.removeFolder", ..._args); },
    onDidChangeFolders: (..._args: unknown[]) => { console.info("[linkdesk-mock] workspace.onDidChangeFolders", ..._args); return () => {}; },
    onDidChangeActiveWorkspace: (..._args: unknown[]) => { console.info("[linkdesk-mock] workspace.onDidChangeActiveWorkspace", ..._args); return () => {}; },
  },
  filesystem: {
    readTextFile: async (..._args: unknown[]) => { console.info("[linkdesk-mock] filesystem.readTextFile", ..._args); return ""; },
    writeTextFile: async (..._args: unknown[]) => { console.info("[linkdesk-mock] filesystem.writeTextFile", ..._args); },
    exists: async (..._args: unknown[]) => { console.info("[linkdesk-mock] filesystem.exists", ..._args); return false; },
    createDir: async (..._args: unknown[]) => { console.info("[linkdesk-mock] filesystem.createDir", ..._args); },
    copy: async (..._args: unknown[]) => { console.info("[linkdesk-mock] filesystem.copy", ..._args); },
    rename: async (..._args: unknown[]) => { console.info("[linkdesk-mock] filesystem.rename", ..._args); },
    remove: async (..._args: unknown[]) => { console.info("[linkdesk-mock] filesystem.remove", ..._args); },
    listDir: async (..._args: unknown[]) => { console.info("[linkdesk-mock] filesystem.listDir", ..._args); return []; },
    readBinaryFile: async (..._args: unknown[]) => { console.info("[linkdesk-mock] filesystem.readBinaryFile", ..._args); },
    writeBinaryFile: async (..._args: unknown[]) => { console.info("[linkdesk-mock] filesystem.writeBinaryFile", ..._args); },
    watch: async (..._args: unknown[]) => { console.info("[linkdesk-mock] filesystem.watch", ..._args); },
    readdir: async (..._args: unknown[]) => { console.info("[linkdesk-mock] filesystem.readdir", ..._args); return []; },
  },
  path: {
    appDataDir: async (..._args: unknown[]) => { console.info("[linkdesk-mock] path.appDataDir", ..._args); return ""; },
    normalize: (..._args: unknown[]) => { console.info("[linkdesk-mock] path.normalize", ..._args); return ""; },
    join: (..._args: unknown[]) => { console.info("[linkdesk-mock] path.join", ..._args); return ""; },
    basename: (..._args: unknown[]) => { console.info("[linkdesk-mock] path.basename", ..._args); return ""; },
    dirname: (..._args: unknown[]) => { console.info("[linkdesk-mock] path.dirname", ..._args); return ""; },
    extname: (..._args: unknown[]) => { console.info("[linkdesk-mock] path.extname", ..._args); return ""; },
  },
  env: {
    get: async (..._args: unknown[]) => { console.info("[linkdesk-mock] env.get", ..._args); },
  },
  search: {
    searchFiles: async (..._args: unknown[]) => { console.info("[linkdesk-mock] search.searchFiles", ..._args); return []; },
  },
  encoding: {
    detect: async (..._args: unknown[]) => { console.info("[linkdesk-mock] encoding.detect", ..._args); return ""; },
    decode: async (..._args: unknown[]) => { console.info("[linkdesk-mock] encoding.decode", ..._args); return ""; },
    encode: async (..._args: unknown[]) => { console.info("[linkdesk-mock] encoding.encode", ..._args); },
  },
  decorations: {
    registerProvider: (..._args: unknown[]) => { console.info("[linkdesk-mock] decorations.registerProvider", ..._args); },
    unregisterProvider: (..._args: unknown[]) => { console.info("[linkdesk-mock] decorations.unregisterProvider", ..._args); },
    getDecoration: async (..._args: unknown[]) => { console.info("[linkdesk-mock] decorations.getDecoration", ..._args); },
    onDidChange: (..._args: unknown[]) => { console.info("[linkdesk-mock] decorations.onDidChange", ..._args); return () => {}; },
  },
  fileAssociation: {
    getPluginFor: async (..._args: unknown[]) => { console.info("[linkdesk-mock] fileAssociation.getPluginFor", ..._args); },
  },
  langDef: {
    get: async (..._args: unknown[]) => { console.info("[linkdesk-mock] langDef.get", ..._args); },
  },
  lsp: {
    spawn: async (..._args: unknown[]) => { console.info("[linkdesk-mock] lsp.spawn", ..._args); return ""; },
    write: (..._args: unknown[]) => { console.info("[linkdesk-mock] lsp.write", ..._args); },
    dispose: async (..._args: unknown[]) => { console.info("[linkdesk-mock] lsp.dispose", ..._args); },
    onData: (..._args: unknown[]) => { console.info("[linkdesk-mock] lsp.onData", ..._args); return () => {}; },
  },
  protocol: {
    listProtocols: async (..._args: unknown[]) => { console.info("[linkdesk-mock] protocol.listProtocols", ..._args); return []; },
    getActiveProtocolId: async (..._args: unknown[]) => { console.info("[linkdesk-mock] protocol.getActiveProtocolId", ..._args); return ""; },
    setActiveProtocolId: async (..._args: unknown[]) => { console.info("[linkdesk-mock] protocol.setActiveProtocolId", ..._args); },
  },
  viewContainer: {
    getViewContainer: async (..._args: unknown[]) => { console.info("[linkdesk-mock] viewContainer.getViewContainer", ..._args); },
    getViews: async (..._args: unknown[]) => { console.info("[linkdesk-mock] viewContainer.getViews", ..._args); return []; },
    getView: async (..._args: unknown[]) => { console.info("[linkdesk-mock] viewContainer.getView", ..._args); },
    registerView: async (..._args: unknown[]) => { console.info("[linkdesk-mock] viewContainer.registerView", ..._args); },
  },
  plugins: {
    resolvePath: async (..._args: unknown[]) => { console.info("[linkdesk-mock] plugins.resolvePath", ..._args); return ""; },
    resolveEntry: async (..._args: unknown[]) => { console.info("[linkdesk-mock] plugins.resolveEntry", ..._args); },
    listDirs: async (..._args: unknown[]) => { console.info("[linkdesk-mock] plugins.listDirs", ..._args); return []; },
    listAll: async (..._args: unknown[]) => { console.info("[linkdesk-mock] plugins.listAll", ..._args); return []; },
    listDisabledDirs: async (..._args: unknown[]) => { console.info("[linkdesk-mock] plugins.listDisabledDirs", ..._args); return []; },
    readManifest: async (..._args: unknown[]) => { console.info("[linkdesk-mock] plugins.readManifest", ..._args); return ""; },
    readAllManifests: async (..._args: unknown[]) => { console.info("[linkdesk-mock] plugins.readAllManifests", ..._args); },
    packageDownload: async (..._args: unknown[]) => { console.info("[linkdesk-mock] plugins.packageDownload", ..._args); },
    packageExtract: async (..._args: unknown[]) => { console.info("[linkdesk-mock] plugins.packageExtract", ..._args); },
    packageUpdateCheck: async (..._args: unknown[]) => { console.info("[linkdesk-mock] plugins.packageUpdateCheck", ..._args); },
    packageStageUpdate: async (..._args: unknown[]) => { console.info("[linkdesk-mock] plugins.packageStageUpdate", ..._args); },
    packageCommitUpdate: async (..._args: unknown[]) => { console.info("[linkdesk-mock] plugins.packageCommitUpdate", ..._args); },
  },
  pluginManager: {
    list: async (..._args: unknown[]) => { console.info("[linkdesk-mock] pluginManager.list", ..._args); return []; },
    enable: async (..._args: unknown[]) => { console.info("[linkdesk-mock] pluginManager.enable", ..._args); },
    disable: async (..._args: unknown[]) => { console.info("[linkdesk-mock] pluginManager.disable", ..._args); },
    uninstall: async (..._args: unknown[]) => { console.info("[linkdesk-mock] pluginManager.uninstall", ..._args); },
    install: async (..._args: unknown[]) => { console.info("[linkdesk-mock] pluginManager.install", ..._args); },
    installWithProgress: async (..._args: unknown[]) => { console.info("[linkdesk-mock] pluginManager.installWithProgress", ..._args); },
    reinstall: async (..._args: unknown[]) => { console.info("[linkdesk-mock] pluginManager.reinstall", ..._args); },
    getDisabled: async (..._args: unknown[]) => { console.info("[linkdesk-mock] pluginManager.getDisabled", ..._args); return []; },
    getUninstalled: async (..._args: unknown[]) => { console.info("[linkdesk-mock] pluginManager.getUninstalled", ..._args); return []; },
    isDisabled: async (..._args: unknown[]) => { console.info("[linkdesk-mock] pluginManager.isDisabled", ..._args); return false; },
    update: async (..._args: unknown[]) => { console.info("[linkdesk-mock] pluginManager.update", ..._args); },
    checkUpdates: async (..._args: unknown[]) => { console.info("[linkdesk-mock] pluginManager.checkUpdates", ..._args); },
    notifyManifestChanged: (..._args: unknown[]) => { console.info("[linkdesk-mock] pluginManager.notifyManifestChanged", ..._args); },
  },
  bridge: {
    onRequest: (..._args: unknown[]) => { console.info("[linkdesk-mock] bridge.onRequest", ..._args); return () => {}; },
    respond: (..._args: unknown[]) => { console.info("[linkdesk-mock] bridge.respond", ..._args); },
    broadcast: (..._args: unknown[]) => { console.info("[linkdesk-mock] bridge.broadcast", ..._args); },
    notifyConfigChanged: (..._args: unknown[]) => { console.info("[linkdesk-mock] bridge.notifyConfigChanged", ..._args); },
  },
  pool: {
    pushLayout: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.pushLayout", ..._args); },
    onReady: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.onReady", ..._args); return () => {}; },
    toggleDevTools: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.toggleDevTools", ..._args); },
    onSidebarAction: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.onSidebarAction", ..._args); return () => {}; },
    onTabAction: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.onTabAction", ..._args); return () => {}; },
    onTabBarRects: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.onTabBarRects", ..._args); return () => {}; },
    onDragPosition: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.onDragPosition", ..._args); return () => {}; },
    pushAdsorbHint: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.pushAdsorbHint", ..._args); },
    onAdsorbIndex: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.onAdsorbIndex", ..._args); return () => {}; },
    pushQuickPick: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.pushQuickPick", ..._args); },
    onQuickPickAction: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.onQuickPickAction", ..._args); return () => {}; },
    pushDialog: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.pushDialog", ..._args); },
    onDialogAction: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.onDialogAction", ..._args); return () => {}; },
    pushFloatingPanel: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.pushFloatingPanel", ..._args); },
    onFloatingPanelAction: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.onFloatingPanelAction", ..._args); return () => {}; },
    onMemoryPressure: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.onMemoryPressure", ..._args); return () => {}; },
    createWindow: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.createWindow", ..._args); },
    closeWindow: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.closeWindow", ..._args); },
    onWindowClosed: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.onWindowClosed", ..._args); return () => {}; },
    onWindowBoundsChanged: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.onWindowBoundsChanged", ..._args); return () => {}; },
    onLayout: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.onLayout", ..._args); return () => {}; },
    ready: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.ready", ..._args); },
    sidebarAction: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.sidebarAction", ..._args); },
    tabAction: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.tabAction", ..._args); },
    tabBarRects: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.tabBarRects", ..._args); },
    dragPosition: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.dragPosition", ..._args); },
    onAdsorbHint: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.onAdsorbHint", ..._args); return () => {}; },
    adsorbIndex: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.adsorbIndex", ..._args); },
    registerBeforeClose: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.registerBeforeClose", ..._args); },
    unregisterBeforeClose: (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.unregisterBeforeClose", ..._args); },
    beforeClose: async (..._args: unknown[]) => { console.info("[linkdesk-mock] pool.beforeClose", ..._args); return false; },
  },
  window: {
    minimize: (..._args: unknown[]) => { console.info("[linkdesk-mock] window.minimize", ..._args); },
    maximize: (..._args: unknown[]) => { console.info("[linkdesk-mock] window.maximize", ..._args); },
    unmaximize: (..._args: unknown[]) => { console.info("[linkdesk-mock] window.unmaximize", ..._args); },
    close: (..._args: unknown[]) => { console.info("[linkdesk-mock] window.close", ..._args); },
    setZoom: (..._args: unknown[]) => { console.info("[linkdesk-mock] window.setZoom", ..._args); },
    toggleDevTools: async (..._args: unknown[]) => { console.info("[linkdesk-mock] window.toggleDevTools", ..._args); },
    isMaximized: async (..._args: unknown[]) => { console.info("[linkdesk-mock] window.isMaximized", ..._args); return false; },
    onMaximizeChange: (..._args: unknown[]) => { console.info("[linkdesk-mock] window.onMaximizeChange", ..._args); return () => {}; },
    setAlwaysOnTop: (..._args: unknown[]) => { console.info("[linkdesk-mock] window.setAlwaysOnTop", ..._args); },
    isAlwaysOnTop: async (..._args: unknown[]) => { console.info("[linkdesk-mock] window.isAlwaysOnTop", ..._args); return false; },
    onAlwaysOnTopChange: (..._args: unknown[]) => { console.info("[linkdesk-mock] window.onAlwaysOnTopChange", ..._args); return () => {}; },
  },
  shell: {
    showItemInFolder: async (..._args: unknown[]) => { console.info("[linkdesk-mock] shell.showItemInFolder", ..._args); },
    openInTerminal: async (..._args: unknown[]) => { console.info("[linkdesk-mock] shell.openInTerminal", ..._args); },
    startDrag: (..._args: unknown[]) => { console.info("[linkdesk-mock] shell.startDrag", ..._args); },
  },
  hotExit: {
    save: async (..._args: unknown[]) => { console.info("[linkdesk-mock] hotExit.save", ..._args); },
    load: async (..._args: unknown[]) => { console.info("[linkdesk-mock] hotExit.load", ..._args); },
    clear: async (..._args: unknown[]) => { console.info("[linkdesk-mock] hotExit.clear", ..._args); },
  },
  getFilePath: (..._args: unknown[]) => { console.info("[linkdesk-mock] getFilePath", ..._args); return ""; },
  panel: {
    reveal: async (..._args: unknown[]) => { console.info("[linkdesk-mock] panel.reveal", ..._args); },
    revealFloating: async (..._args: unknown[]) => { console.info("[linkdesk-mock] panel.revealFloating", ..._args); },
  },
  settings: {
    list: async (..._args: unknown[]) => { console.info("[linkdesk-mock] settings.list", ..._args); return []; },
    getActive: async (..._args: unknown[]) => { console.info("[linkdesk-mock] settings.getActive", ..._args); },
    setActive: async (..._args: unknown[]) => { console.info("[linkdesk-mock] settings.setActive", ..._args); },
  },
  factorySlots: {
    listRoles: async (..._args: unknown[]) => { console.info("[linkdesk-mock] factorySlots.listRoles", ..._args); return []; },
    list: async (..._args: unknown[]) => { console.info("[linkdesk-mock] factorySlots.list", ..._args); return []; },
    getActive: async (..._args: unknown[]) => { console.info("[linkdesk-mock] factorySlots.getActive", ..._args); },
    setActive: async (..._args: unknown[]) => { console.info("[linkdesk-mock] factorySlots.setActive", ..._args); },
  },
  app: {
    getVersion: async (..._args: unknown[]) => { console.info("[linkdesk-mock] app.getVersion", ..._args); return ""; },
  },
};
